-- 코드를 입력하세요
# USER_INFO : 가입한 회원 정보를 담은 : 회원 ID, 성별(NULL,0,1), 나이, 가입일
# ONLINE_SALE : 온라인 상품 판매 정보를 담은 : 상품 판매 ID, 회원 ID, 상품 ID, 판매량, 판매일
# SELECT A.ONLINE_SALE_ID, A.USER_ID,	A.PRODUCT_ID, A.SALES_AMOUNT, A.SALES_DATE
# FROM ONLINE_SALE AS A LEFT JOIN USER_INFO AS B
# ON A.USER_ID = B.USER_ID

SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
ROUND(COUNT(DISTINCT USER_ID)/(
    SELECT COUNT(*)
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
), 1)AS PURCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021)
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH