-- 코드를 작성해주세요
# SELECT ROUTE, 
#     CONCAT(ROUND(SUM(D_BETWEEN_DIST),1), 'km') AS 'TOTAL_DISTANCE', 
#     CONCAT(ROUND(AVG(D_BETWEEN_DIST),2), 'km') AS 'AVERAGE_DISTANCE'
# FROM SUBWAY_DISTANCE
# GROUP BY ROUTE
# ORDER BY ROUND(AVG(D_BETWEEN_DIST),2) DESC

select ROUTE,
    concat(round(sum(D_BETWEEN_DIST), 1), 'km') 'TOTAL_DISTANCE',
    concat(round(avg(D_BETWEEN_DIST), 2), 'km') 'AVERAGE_DISTANCE'
from SUBWAY_DISTANCE
group by route
order by round(sum(D_BETWEEN_DIST), 2) desc