-- 코드를 작성해주세요
SELECT COUNT(ID) AS FISH_COUNT, (
    SELECT FISH_NAME
    FROM FISH_NAME_INFO
    WHERE FISH_NAME_INFO.FISH_TYPE=FISH_INFO.FISH_TYPE 
) AS FISH_NAME
FROM FISH_INFO
GROUP BY FISH_NAME
ORDER BY FISH_COUNT DESC
# SELECT COUNT(*)
# FROM FISH_INFO
#         WHERE FISH_NAME_INFO.FISH_TYPE=FISH_INFO.FISH_TYPE 
#         GROUP BY FISH_TYPE) AS FISH_COUNT, FISH_NAME
        
        
# SELECT COUNT(TIME) AS FISH_COUNT, FISH_NAME
# FROM FISH_INFO
# JOIN FISH_NAME_INFO
# USING(FISH_TYPE)
# GROUP BY FISH_NAME
# ORDER BY FISH_COUNT DESC