-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(A.SALES) AS TOTAL_SALES
FROM BOOK_SALES AS A LEFT JOIN BOOK AS B
ON A.BOOK_ID = B.BOOK_ID
WHERE A.SALES_DATE LIKE '2022-01-%'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY