-- 코드를 입력하세요
# CAR_RENTAL_COMPANY_CAR 자동차들의 정보
# 자동차 ID, 자동차 종류, 일일 대여 요금(원), 자동차 옵션 리스트

# CAR_RENTAL_COMPANY_RENTAL_HISTORY 대여 기록 정보
# 대여 기록 ID, 자동차 ID, 대여 시작일, 대여 종료일

# CAR_RENTAL_COMPANY_DISCOUNT_PLAN 자동차 종류 별 대여 기간 종류 별 할인 정책 정보
# 요금 할인 정책 ID, 자동차 종류, 대여 기간 종류, 할인율(%)
SELECT A.HISTORY_ID, 
        ROUND((DATEDIFF(END_DATE,START_DATE)+1)*(A.DAILY_FEE*(100-COALESCE(DISCOUNT_RATE, 0)))/100, 0) AS FEE
FROM (
    SELECT C.CAR_ID, C.CAR_TYPE, H.START_DATE, H.END_DATE, H.HISTORY_ID, C.DAILY_FEE,
    CASE WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN '90일 이상'
         WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN '30일 이상'
         WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN '7일 이상' 
    END AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H LEFT JOIN CAR_RENTAL_COMPANY_CAR AS C 
    ON C.CAR_ID = H.CAR_ID
    WHERE CAR_TYPE = '트럭') AS A 
LEFT JOIN (
    SELECT DURATION_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭') AS B
ON A.DURATION = B.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC