-- 코드를 입력하세요
SELECT A.APNT_NO, A.PT_NAME, A.PT_NO, A.MCDP_CD, C.DR_NAME, A.APNT_YMD
FROM (SELECT A.APNT_NO, B.PT_NAME, B.PT_NO, A.MCDP_CD, A.APNT_YMD, A.MDDR_ID, A.APNT_CNCL_YN
    FROM APPOINTMENT AS A JOIN PATIENT AS B
    ON A.PT_NO = B.PT_NO
    WHERE A.APNT_CNCL_YN = 'N') AS A JOIN DOCTOR AS C
ON A.MDDR_ID = C.DR_ID
WHERE(A.APNT_YMD LIKE '2022-04-13%') AND  A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD
